name = "Xeno's SMP"
author = "xeno"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea513f116ebf33c73fb4f178dc9ae4c85ef406cb204f77d2e671e7f38f34df74"

[versions]
forge = "47.4.22"
minecraft = "1.20.1"
