name = "Xeno's SMP"
author = "xeno"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f990a19e6a1b95c45dd022aa0e3847efee068039ec7dfcfefb3d88efcb44002"

[versions]
forge = "47.4.22"
minecraft = "1.20.1"
