name = "Xeno's SMP"
author = "xeno"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "178b75f4f32a23d9615a46392c67e404c951c8024cd1678c0e8cf3c3919e51b3"

[versions]
forge = "47.4.22"
minecraft = "1.20.1"
